app/models/Forum.py
from sqlalchemy import String, Integer, Column, ForeignKey
from sqlalchemy.orm import relationship


from app.models import Base
from .Base_model import BaseModel
from app.utils.slash_helper import sanitize_key

class Forum(Base, BaseModel):
    
    __tablename__ = 'forum'
    
    title = Column(String(length=128), nullable=False, unique=True)
    description = Column(String(length=1024), nullable=False, unique=False)
    slush = Column(String(128))
    owner_id = Column(Integer,ForeignKey('user.id'), nullable=False)
    replies = relationship('Reply', backref='forum', lazy=True)

    def __repr__(self):
        return f'Title:{self.title} Desc:{self.description}' 
  
    def __init__(self,schema):

        if not isinstance(schema, dict):
            raise ArgumentError("Schema should be a dictionary")

        for attribute, value in schema.items():
            if hasattr(self, attribute) and getattr(self, attribute) != value:
                    setattr(self, attribute, value) 

        if not self.slush:
           self.slush = sanitize_key(self.title)

app/routes/auth_view.py
from flask import render_template, redirect, url_for, Blueprint, flash, request, make_response

from flask_login import login_required, login_user, logout_user

from app.models import *
from app.form import RegisterForm, LoginForm
from app.database import session       
from flask_bcrypt import check_password_hash


auth = Blueprint('auth', __name__, template_folder="app/templates/", url_prefix="/auth")

@auth.route('/register/', methods=['GET', 'POST'])
def register():
    
    form = RegisterForm(request.form)

    if request.method == 'POST' and form.validate():
        if form.password1.data == form.password2.data:
            new_user = User({ 
                "name" : form.username.data, 
                "email" : form.email_address.data,
                "password" : form.password1.data
                })
            session.add(new_user)
            session.commit()
            login_user(new_user)
            
            flash("Thanks for registering")
            
            return redirect(url_for('views.home'))
        flash("Password not match!")    

    return render_template('register.html', form = form)
    
@auth.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    
    if request.method == "POST" and form.validate():
        user = User.query.filter(User.email == form.email_address.data).first()
        if user:
            if check_password_hash(user.password, form.password.data):
                login_user(user)
                flash(f"Welcome {user.name}", category='success')
                return redirect(url_for('views.home'))
            flash("Incorrect email or password. Please try again.", category='danger')    
        else:
            flash("Incorrect email or password. Please try again.", category='danger')
            
    return render_template('login.html',form=form)   

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash("Logged out", category='info')
    return redirect(url_for('views.home'))

app/routes/forum_view.py
from flask import render_template, redirect, url_for, Blueprint, request, abort, flash, make_response
from app.models import *
from app.form import CreateForumForm, UpdateForumForm
from app.database import session

from flask_login import login_required, current_user

from app.form import ReplyForm
forum_blueprint = Blueprint('forum_blueprint', __name__, template_folder="app/templates/",url_prefix="/forum")

@forum_blueprint.route("/")
def all_forum():
    
    forums = Forum.query.all()
    return render_template("forum.html" ,forums = forums)

@forum_blueprint.route("/new-forum/", methods=['GET', 'POST'])
@login_required
def create_forum():
    form = CreateForumForm(request.form)
    
    if request.method == 'POST' and form.validate():
        new_forum = Forum({'title':form.title.data, 'description' : form.description.data,'owner_id' :  current_user._get_current_object().id})
        session.add(new_forum)
        session.commit()
        return redirect(url_for('views.home'))
    tags = TagModel.query.all()
    #return render_template("forum_create.html", form = form, tags = tags)
    response = make_response(render_template("forum_create.html",  form = form, tags = tags))
    return response

@forum_blueprint.route("/created-forum/")
@login_required
def user_forum():
    user = current_user._get_current_object()
    forums = user.forums
    return render_template('created_forum.html',forums = forums)

@forum_blueprint.route("/<slush>/", methods=['GET','POST'])
def single_forum(slush):
    form = ReplyForm(request.form)
    forum = Forum.query.filter(Forum.slush == slush).one()

    user_authentication()

    if request.method == 'POST' and form.validate():
        form_dict = request.form.to_dict()
        new_reply = Reply({'parent_id': current_user._get_current_object().id,'forum_id':forum.id})
        if form_dict:
            for key, value in form_dict.items():
                if hasattr(new_reply, key) and getattr(new_reply, key) != value:
                    setattr(new_reply, key, value)
            session.add(new_reply)
            session.commit()
            flash(f"Created new reply", category='success');

    if not forum:
      abort(404)
    return render_template("single_forum.html", forum = forum, form = form)

@forum_blueprint.route("/update-forum/<id>/",methods=["POST", "GET"])
@login_required
def update_user_forum(id):

    form = UpdateForumForm(request.form)
    forum = Forum.query.get(id)

    if form.validate_on_submit():
        forum.title = form.title.data
        forum.description = form.description.data
        session.commit()
        return redirect(url_for("forum_blueprint.user_forum"))

    return render_template("update_forum.html", form = form, forum = forum)

@forum_blueprint.route("/created-forum/delete/<id>/", methods=["GET"])
@login_required
def delete_forum(id):
    
    forum = Forum.query.filter(Forum.id == id).delete()
    session.commit()
    flash("One forum have been deleted.", category="success")
    return redirect(url_for("forum_blueprint.user_forum"))


def user_authentication():
    if request.method == 'POST' and current_user.is_anonymous:
        flash("Please login to continue.", category='info')
        return redirect(url_for('auth.login'))

app/templates/all_replies.html
{% extends "index.html" %}

{% block content %}
<h4 class="text-center shadow-sm" style="color: rgb(157, 129, 3);">{{forum.title}}</h4>
{% for reply in replies %}
<div class="reply-wrapper">
    <div class="reply">
        <p style="color: rgb(13, 23, 66);"><img src="/static/thanos.jpg" style="width: 3ch; height: 3ch; border-radius:50%;" ><span style="color: rgb(171, 21, 2);">{{reply.user.name}}</span></p>
        <h5 class="small">{{ reply.title }}</h5>
        <p class="shadow-sm">{{reply.description}}</p>
    </div>
</div>
{% endfor %}
{% if not replies %}
    <h5 class="small" style="color: darkblue;">No reply yet. Be the first to reply on this post.</h5>
{% endif %}
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    {% block title %}
        
    {% endblock %}
</head>
<body>

    <!--------------------------Nav Bar--------------------------->
    <header>
        <nav>
            <ul>
                <a class="nav-btn active" id="nav-btn" href="{{url_for('views.home')}}">Home</a>
                <a class="nav-btn" id="nav-btn" href="{{ url_for('forum_blueprint.all_forum') }}">Forum</a>
                <a class="nav-btn" id="nav-btn" href="#">About</a>
                <a class="nav-btn" id="nav-btn" href="#">Service</a>
                
                {% if current_user.is_authenticated %}
                <a class="nav-btn login-btn" id="nav-btn" href="{{ url_for('auth.logout') }}">Logout</a>
                {% else %}
                <a class="nav-btn login-btn" id="nav-btn" href="{{ url_for('auth.login') }}">Login</a>
                {% endif %}
            </ul>
        </nav>
    </header>
    
    <!----------Contents----------------->
    {% with flashed_messages = get_flashed_messages(with_categories=true) %}
    {% if flashed_messages %}
    {% for message in flashed_messages %}
    <div class="alert alert-{{ message[0] }} text-center">
    {{ message[1] }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}  
    <div class="container">
    {% block content %}
        
    {% endblock %}
    </div>

</body>

<script src="{{ url_for('static', filename='index.js') }}"></script>
</html>

app/templates/created_forum.html
{% extends 'base.html' %}

{% block content %}
<h2 style="color: rgba(199, 181, 18, 0.85); font-size: medium; ">My forum</h2>
<table>
    <tr>
        <th>No</th>
        <th>Title</th>
        <th>Update</th>
        <th>Delete</th>
    </tr>
    {% for forum in forums %}
        <tr>
            <td><a href="/forum/{{forum.slush}}" style="color: rgba(18, 7, 103, 0.85);"></a>{{forum.id}}</td>
            <td><a href="/forum/{{forum.slush}}" style="color: rgba(18, 7, 103, 0.85);">{{forum.title}}</a></td>
            <td><a href="/forum/update-forum/{{forum.id}}/" style="color: rgba(18, 7, 103, 0.85);">Update</a></td>
            <td><a href="/forum/created-forum/delete/{{forum.id}}/" style="color: rgba(18, 7, 103, 0.85);">Delete</a></td>
        </tr>
    {% endfor %}
</table>
{% endblock %}

app/templates/forum.html
{% extends "index.html" %}

{% block content %}
<h4 class="text-center shadow-sm" style="color: rgb(157, 129, 3);">Top user interact of the week</h4>
{% for forum in forums %}
{% if forum %}

<div class="forum-wrapper">
    <div class="forum">
        <h5><a style="color: rgb(52, 15, 1);" href="/forum/{{forum.slush}}/">{{ forum.title }}</a></h5>
        <!-- <p>{{forum.description}}</p> -->
        <p style="color: rgb(13, 23, 66);">Author: <span style="color: rgb(171, 21, 2);">{{forum.owner.name}}</span></p>
    </div>

    <div class="reply small shadow-sm" >
       <p ><a href="/reply/{{forum.slush}}/" style="color: rgb(14, 25, 44);">See reply</a></p>
    </div>
</div>

{% else %}
    <h3>There was an error occured while rying to load forum please try again later.</h3>
{% endif %}

{% endfor %}
{% endblock %}

app/templates/forum_create.html
{% extends 'base.html' %}

{% block title %}
<title>Create new forum</title>
{% endblock %}

{% block content %}
<form action="/forum/new-forum/" method="post">
    {{form.csrf_token}}
    {{form.title(placeholder = "Forum title", class = "form-control")}}
    <br>
    {{form.description(class="form-control", placeholder="Description")}}
    <br>
    {% if tags %}
    <div class="text-center">
    <label for="tags">Choose a Tag:</label>
    <select name="tag" class="text-center">
        {% for tag in tags%}
            <option value="{{tag.name}}">{{tag.name}}</option>
        {% endfor %}
    </select>
    </div>
    {% endif %}
    <br>
    {{form.create(class="btn btn-primary btn-block btn-sm")}}
    
</form>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block title %}

<title>Forum Home Page</title>
{% endblock %}
{% block content %}

<form action="searched_forum" class="search" method="post">
    <input class="searchBox" type="text" value="what are you looking for?">
    <button type="submit" class="searchBtn">Search</button>
</form>


<!--------------------------Top Search Category--------------------------->
<section class="top-search">

    <div class="top-forum">
        <div>
            <img class="forumImg shadow-sm" src="{{ url_for('static', filename='pp.png') }}" alt="forumImg">
            <h4>Lorem ipsum dolor sit amet consectetur adi </h4>
        </div>
        <div class="forumInfo shadow-sm">
            <div class="authorProfile">
                <img src="{{ url_for('static', filename='thanos.jpg') }}" alt="userIcon">
                <h4>Thanos</h4>
            </div>
            
            <div class="forumReaction">
                <div>
                    <img src="{{ url_for('static', filename='comment.png') }}" alt="reply">
                    <h5>3789</h5>
                </div>
                <div>
                    <img src="{{ url_for('static', filename='react.png') }}" alt="likeIcon">
                    <h5>1000</h5>
                </div>
            </div>
        </div>
    </div>



</section>


<!--------------------------Footer--------------------------->

<section class="footer">
    <div class="web-link">
        <a href="#"><img src="" alt="">YouTube</a>
        <a href="#"><img src="" alt="">Facebook</a>
        <a href="#"><img src="" alt="">Discord</a>
        <a href="#"><img src="" alt="">Twitter</a>
    </div>
</section>
{% endblock %}
  

app/templates/login.html
{% extends 'base.html' %}

{% block title %}
<title>Login</title>
{% endblock %}

{% block content %}
    <form action="/auth/login/" method="POST">
        
        {{ form.csrf_token }}
        {{form.email_address(class="form-control", placeholder="Email Address")}}
        {{form.password(class="form-control", placeholder="Password")}}
        {{form.sign_in(class="btn btn-primary btn-block btn-sm")}}

    </form>
    <br>
    <div class="text-center">
        <p>Don't have an account?</p>
        <a class="btn-block btn-light" href="{{ url_for('auth.register') }}">Create Account</a>
    </div>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

{% block title %}
<title>Register New Account</title>
{% endblock %}

{% block content %}

    {% macro render_field(field) %}
    <dt>{{ field.label }}
    <dd>{{ field(**kwargs)|safe }}
    {% if field.errors %}
    <ul class="errors">
    {% for error in field.errors %}
        <li>{{ error }}</li>
    {% endfor %}
    </ul>
    {% endif %}
    </dd>
    {% endmacro %}

    <form action="/auth/register/" method="post">
        {{ form.csrf_token }}
        {{form.username(class="form-control", placeholder="Username")}}
        {{form.email_address(class="form-control", placeholder="Email Address")}}
        {{form.password1(class="form-control", placeholder="Create Password")}}
        {{form.password2(class="form-control", placeholder="Confirm Password")}}
        {{form.accept_tos}} 
        <p>{{form.accept_tos.label}}</p>
        {{form.create(class="form-control btn btn-primary btn-block btn-sm")}}
    </form>

    <br>
    <div class="text-center">
        <p>Already have an account?</p>
        <a class="btn-block btn-light" href="{{ url_for('auth.login') }}">Login</a>
    </div>

{% endblock %}

app/templates/single_forum.html
{% extends 'base.html'%}

{% block content%}

<h2 style="color: rgba(199, 181, 18, 0.85); font-size: medium; ">{{forum.title}}</h2>
<br>
<p style="color: rgba(18, 7, 103, 0.85);">{{forum.description}}</p>

<div id="reply-form">
    <form method="post" action="/forum/{{forum.slush}}/">
        {{form.csrf_token}}
      <div class="form-group">
        <label for="forum-title">Title</label>
        <input
          type="text"
          name="title"
          class="form-control"
          id="forum-title"
          aria-describedby="emailHelp"
          value="{{forum.title}}"
        />
        <small id="emailHelp" class="form-text text-muted"
          >We'll never share your email with anyone else.</small
        >
      </div>
      <div class="form-group">
        <label for="reply-descrition">Description</label>
        <textarea
          class="form-control"
          id="reply-description"
          rows="3"
          name="description"
        ></textarea>
      </div>
      <button type="submit" class="btn btn-primary">Add reply</button>
    </form>
  </div>

{% endblock %}

app/templates/update_forum.html
{% extends 'base.html' %}

{% block title %}
<title>Create new forum</title>
{% endblock %}

{% block content %}
<form action="/forum/update-forum/{{forum.id}}/" method="post">
    {{form.csrf_token}}
    {{form.title(value = forum.title, class = "form-control")}}
    <br>
    {{form.description(value = forum.description, class="form-control",  rows=4)}}
    <br>
    {{form.update(class="btn btn-primary btn-block btn-sm" )}}
</form>
{% endblock %}